# Generated by Django 2.0.4 on 2018-06-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_troom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troom',
            name='personNum',
            field=models.IntegerField(default=0),
        ),
    ]
