# Generated by Django 2.0.4 on 2018-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180620_1802'),
        ('game', '0003_auto_20180620_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='hall',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('allNum', models.IntegerField(default=0)),
                ('hallplayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.TUser')),
            ],
        ),
    ]
