# Generated by Django 2.0.4 on 2018-06-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180620_1802'),
        ('game', '0004_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='hallPlayer',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hallplayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.TUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='hall',
            name='hallplayer',
        ),
        migrations.DeleteModel(
            name='hall',
        ),
    ]
