# Generated by Django 2.0.4 on 2018-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180623_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallplayer',
            name='roomplayerId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
