# Generated by Django 2.0.4 on 2018-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_hallplayer_roomplayerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='troom',
            name='firstpersonId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='troom',
            name='secondpersonId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
