# Generated by Django 2.0.4 on 2018-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20180624_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('resultId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userId', models.CharField(max_length=50)),
                ('opuserId', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
