# Generated by Django 2.0.4 on 2018-06-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresult',
            name='dateCreated',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
