# Generated by Django 2.0.4 on 2018-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('aiWinTime', models.IntegerField(max_length=12)),
                ('aiLoseTime', models.IntegerField(max_length=12)),
                ('pvpWinTime', models.IntegerField(max_length=12)),
                ('pvpLoseTime', models.IntegerField(max_length=12)),
                ('articlePic', models.CharField(max_length=200)),
            ],
        ),
    ]
