# Generated by Django 2.0.4 on 2018-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='aiLoseTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='aiWinTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='pvpLoseTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='pvpWinTime',
            field=models.IntegerField(),
        ),
    ]
